# Generated by Django 6.0 on 2025-12-11 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('core', '0001_initial'),
        ('damages', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='damage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='damage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='damage',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='core.damagereason'),
        ),
        migrations.AddField(
            model_name='damage',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damages_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damage',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damages_rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
