# Generated by Django 6.0 on 2025-12-11 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('supply', 'Supply'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('consumption', 'Consumption'), ('damage', 'Damage'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('max_stock_level', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_perishable', models.BooleanField(default=False)),
                ('shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyInventoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_date', models.DateField()),
                ('count_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counts', to='branches.branch')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_inventory_counts',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyInventoryCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('variance_reason', models.TextField(blank=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.dailyinventorycount')),
            ],
            options={
                'db_table': 'daily_inventory_count_items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('document_number', models.CharField(blank=True, max_length=30)),
                ('partial_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('content_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('content_description', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('incoming_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumption_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('consumption_description', models.TextField(blank=True)),
                ('period_start_date', models.DateField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('last_count_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='branches.branch')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['item__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventory')),
            ],
            options={
                'db_table': 'inventory_batches',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
    ]
